# Generated by Django 3.2.4 on 2021-06-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_payment_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZarinpalPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefID', models.CharField(max_length=255, null=True)),
                ('Authority', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_info', to='orders.order')),
            ],
        ),
    ]
