# Generated by Django 3.2.4 on 2021-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
