# Generated by Django 3.2.4 on 2021-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
